eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: gateway
server:
  port: 8083
zuul:
  routes:
    api-a:
          path: /producer/**
          serviceId: producer
    api-b:
          path: /consumer/**
          serviceId: consumer

